- hosts: localhost
  gather_facts: false
  vars:
    # ansible_python_interpreter: "{{ ansible_playbook_python }}"
    image_name: hello-go
    image_tag: latest

  tasks:
    - name: Build the Hello go image
      docker_image:
        build:
          path: ../Ch2_hello-go-automation
          pull: false
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build

    - name: Run the Hello Go image
      docker_container:
        name: hello-go
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        published_ports:
          - 8180:8180

    - name: Verify Hello Go is responding
      uri:
        url: http://localhost:8180/test
        return_content: true
      register: hello_go_response
      failed_when: "'/test' not in hello_go_response.content"

    # - name: Debug output
    #   debug:
    #     msg: "{{ hello_go_response }}"

    - name: Stop and remove the Hello Go container
      docker_container:
        name: hello-go
        state: absent

