- hosts: localhost
  gather_facts: false
  vars:
    # ansible_python_interpreter: "{{ ansible_playbook_python }}"
    image_name: hello-go
    replicas: 1
    app_state: absent

  tasks:
  #   # Build the hello-go Docker image inside Minikube's environment.
  # - name: Get existing image hash.
  #   shell: |
  #       docker images -q {{ image_name }}
  #   register: image_hash
  #   changed_when: false

  # - name: Build image if it's not already built.
  #   shell: |
  #       docker build -t {{ image_name }} ../hello-go
  #   when: not image_hash.stdout

  - name: Build image and with build args
    community.general.docker_image:
      name: "{{ image_name }}"
      state: present
      build:
        path: .
        # args:
        #   log_volume: /var/log/myapp
        #   listen_port: 8080
      source: build

    # Create Kubernetes resources to run Hello Go.
  - name: Create a Deployment for Hello Go.
    k8s:
      state: "{{ app_state }}"
      definition:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: "{{ image_name }}"
          namespace: default
        spec:
          replicas: "{{ replicas }}"
          selector:
            matchLabels:
              app: "{{ image_name }}"
          template:
            metadata:
              labels:
                app: "{{ image_name }}"
            spec:
              containers:
              - name: "{{ image_name }}"
                image: "{{ image_name }}"
                imagePullPolicy: IfNotPresent
                ports:
                - containerPort: 8180

  - name: Create a Service for Hello Go.
    k8s:
      state: "{{ app_state }}"
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: "{{ image_name }}"
          namespace: default
        spec:
          type: LoadBalancer
          ports:
          - port: 8180
            targetPort: 8180
          selector:
            app: "{{ image_name }}"     

#   post_tasks:
#   - name: Expose Hello Go on the host via Minikube.
#     command: minikube service hello-go --url=true
#     changed_when: false
#     register: minikube_service

#     - debug:
#         msg: "Hello Go URL: {{ minikube_service['stdout_lines'][0] }}"             