---
- hosts: localhost
  gather_facts: false

  vars:
    image_name: hello-go
    replicas: 4

  tasks:
    - name: Scale the hello-go deployment with k8s_scale
      k8s_scale:
        api_version: v1
        kind: Deployment
        name: "{{ image_name }}"
        namespace: default
        replicas: "{{ replicas }}"
        wait: false